name: podcast_search
description: A library for searching for podcasts, parsing podcast RSS feeds and obtaining episodes details. Supports searching via iTunes and PodcastIndex (preview).

version: 0.4.0
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^2.0.13
  convert: ^2.1.1
  crypto: ^2.1.5
  dio: ^3.0.10
  # dart_rss: ^1.1.1+1
  # Temporarily use custom fork required for podcast namespace.
  dart_rss:
    git:
      url: https://github.com/amugofjava/dart-rss
      ref: f0ba7c7
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
